### ISSUE TITLE
I am getting RuntimeWarning: divide by zero encountered in log

### ISSUE THREAD

**Issue by talhaanwarch** [nikdon/pyEntropy#11]
greetings. i am try to use sample entropy for eeg, but i am getting following error
/opt/conda/lib/python3.6/site-packages/pyentrp/entropy.py:178: RuntimeWarning: divide by zero encountered in log
  sampen =  - np.log(Ntemp[1:] / Ntemp[:-1])
/opt/conda/lib/python3.6/site-packages/pyentrp/entropy.py:178: RuntimeWarning: invalid value encountered in true_divide
  sampen =  - np.log(Ntemp[1:] / Ntemp[:-1])

**Comment by nikdon** [comment]
It seems that `Ntemp[1:] / Ntemp[:-1]` gives 0 and it cause the error you've got:

```python
>>> import numpy as np
>>> np.log(0.0)
__main__:1: RuntimeWarning: divide by zero encountered in log
-inf
```

Could you check the data you pass into the function?
