### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by ManiSravaniKothapalli** [nikdon/pyEntropy#12]
Can i know the output format of this function sample_entropy? I am getting an array format as an output.
Can u please explain what does the array indicate?

**Comment by nikdon** [comment]
As per function documentation:
```
    Returns:
        Array of sample entropies:
            SE[k] is ratio "#templates of length k+1" / "#templates of length k"
            where #templates of length 0" = n*(n - 1) / 2, by definition
```

**Comment by siridhathri** [comment]
What does each element of array indicate? Is it the sample entropy considering different number of samples each time or the sample entropy of a group of dataset provided? Please explain

**Comment by nikdon** [comment]
From http://physionet.incor.usp.br/physiotools/sampen/:

> The outputs are the sample entropies of the input, for all epoch lengths of 1 to a specified maximum length, m.

**Comment by siridhathri** [comment]
Thank you!
