### ISSUE TITLE
Multiscale sample entropy: Docstring has dead link

### ISSUE THREAD

**Issue by JohannesWiesner** [nikdon/pyEntropy#20]
Hi! I would love to use your `multiscale_entropy` function :) Just as a sanity check: The [link in your docstring ](https://github.com/nikdon/pyEntropy/blob/9320bcc00989e0b35e89a4b45e8f1ee0487203b6/pyentrp/entropy.py#L178)leads to a dead end. I guess this link also refers to the reference in [`sample_entropy`](https://github.com/nikdon/pyEntropy/blob/9320bcc00989e0b35e89a4b45e8f1ee0487203b6/pyentrp/entropy.py#L134-L135)? Therefore you are using the implementation from Costa et al.? Which again should mean that your function gives the same output as [`neurokit2.entropy_multiscale`](https://github.com/neuropsychology/NeuroKit/blob/5cd089e9d82e6f7fb98d2028e69840aee08f8ab3/neurokit2/complexity/entropy_multiscale.py#L20)? :) I would prefer using pyEntropy over neurokit2 since the latter seems to downgrade my pandas version and your package seems to be more lightweight :)

**Comment by nikdon** [comment]
Hey, unfortunately yes, the link is dead and most probably there is no way to restore what was there. There is a PR #4 which has not progressed for a long time. And it brought up a discussion on the way to calculate MSE. In the PR there is Costa's implementation. I'm encouraging you to take a look there

**Comment by JohannesWiesner** [comment]
Yes, there seem to be a lot of packages out there that implement multiscale sample entropy and refer to Costa et al. Would be interesting to cross-check if they give the same (or at least similar) results. For example, I also discovered the pacakge [EntropyHub ](https://www.entropyhub.xyz/python/Functions/Multiscale.html)yesterday which also seems to have implmemented it.

**Comment by nikdon** [comment]
Added a reference to the web archive in #28
